name: Deployment

concurrency:
  group: github-pages
  cancel-in-progress: true

permissions:
  contents: write
  statuses: write

on:
  workflow_dispatch: {}
  push:
    branches:
      - main

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: github-pages
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
      - name: Installs deps
        run: npm install
      - name: Clean
        run: npm run gh-pages:clean
      - name: Build
        run: npm run gh-pages:build
      - name: Deploy
        run: npm run gh-pages:deploy
